### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by KiwiFPVHarry** [MatAtBread/obscura#7]
Hi,

I am on Buster v10 (Raspberry Pi Zero 2 W), with Camera enabled (and working with Motion). After following your Readme I am getting an error Unexpected token 'C', "Cannot rea"... is not valid JSON when I open the browser and point it to [Raspberry IP]:8000 - I can see the controls, but only a placeholder icon.

![image](https://user-images.githubusercontent.com/58052827/196070629-bb736d8c-b682-4fdb-bcde-c470e7d5108e.png)

I what I see when starting it up - presumably this si the right way to do it via PM2. Any help will be appreciated - trying to get a webcam to work that is less laggy then good old motion.

Cheers
Harry

**Comment by MatAtBread** [comment]
I've not tried on Buster. My Pi zero is on Stretch. I made this choice as apparently the Raspbian camera API changed between versions, and I didn't want to rewrite when Buster shipped.

I don't know if that is the source of your issue, but it might be. I would expect the node-gyp to fail when installing the peer dependency pi-camera-native-ts (you did install that, right?) if the API was no longer compatible as the Linux C headers would be different

**Comment by KiwiFPVHarry** [comment]
Thanks for the reply..thought you were on Buster as per the Readme
(Developed and tested on RaspberryPi buster) and Pi Zero 2 W. Must
have been misreading the info..Sorry again. Have given up and got a
Webcam..but still using the camera on Pi Zero 2 W for the 3D
printer..:) Cheers

**Comment by MatAtBread** [comment]
You're right! And I'm getting too old to remember. It's the other way around. It's running in Buster a Stretch had the new API. But if you've found a solution, that's good.
